# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='phase',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
