# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0002_auto_20170215_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('no_of_qns', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oth.Phase'),
        ),
    ]
