# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0005_auto_20170217_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='no_of_qns',
            field=models.IntegerField(default=0),
        ),
    ]
