# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0006_auto_20170218_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='no_of_qns',
            new_name='max_qns',
        ),
        migrations.AddField(
            model_name='phase',
            name='pool_qns',
            field=models.IntegerField(default=0),
        ),
    ]
