# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0007_auto_20170221_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
