# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0008_auto_20170225_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='clue',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
