# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0009_question_clue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='clue',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
    ]
