# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0010_auto_20170225_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='img', max_length=20),
            preserve_default=False,
        ),
    ]
