# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-11 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0014_auto_20170307_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='images',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
