# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-11 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0015_auto_20180311_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
