# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170215_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cur_phase',
        ),
    ]
