# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oth', '0005_auto_20170217_1646'),
        ('users', '0005_remove_user_cur_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oth.Phase'),
        ),
    ]
