# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170218_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cur_phase',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='oth.Phase'),
        ),
    ]
