# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170218_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cur_qn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curq_related', to='oth.Question'),
        ),
    ]
