# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170219_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='GEC Palakkad', max_length=100, verbose_name='Name of your college'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_last_ans',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of User'),
        ),
    ]
