# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170301_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 1, 13, 11, 45, 448825, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_last_ans',
            field=models.DateTimeField(null=True),
        ),
    ]
