# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_last_ans',
        ),
        migrations.AddField(
            model_name='user',
            name='time_taken',
            field=models.DurationField(null=True),
        ),
    ]
