# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170302_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='user',
            name='date_last_ans',
            field=models.DateTimeField(null=True),
        ),
    ]
