# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170306_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cur_qn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curq_related', to='oth.Question'),
        ),
    ]
