# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20170307_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_qns',
            field=models.ManyToManyField(blank=True, related_name='compq_related', to='oth.Question'),
        ),
    ]
